# Generated by Django 5.2 on 2026-01-07 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Contable', 'Contable'), ('Operario', 'Operario')], default='Operario', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('hectareas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campos',
                'indexes': [models.Index(fields=['nombre'], name='idx_campos_nombre'), models.Index(fields=['hectareas'], name='idx_campos_hectareas')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['nombre'], name='idx_clientes_nombre'), models.Index(fields=['cuit'], name='idx_clientes_cuit'), models.Index(fields=['email'], name='idx_clientes_email')],
            },
        ),
        migrations.CreateModel(
            name='CampoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='api.campo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_asignados', to='api.cliente')),
            ],
            options={
                'db_table': 'campos_cliente',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=255)),
                ('monto_otorgado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('fecha_desembolso', models.DateField()),
                ('estado', models.CharField(default='Activo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creditos',
                'indexes': [models.Index(fields=['entidad'], name='idx_creditos_entidad'), models.Index(fields=['estado'], name='idx_creditos_estado'), models.Index(fields=['fecha_desembolso'], name='idx_creditos_fecha')],
            },
        ),
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='api.credito')),
            ],
            options={
                'db_table': 'cuotas_credito',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='api.cliente')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.factura')),
            ],
            options={
                'db_table': 'factura_items',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insumos',
                'indexes': [models.Index(fields=['nombre'], name='idx_insumos_nombre'), models.Index(fields=['categoria'], name='idx_insumos_cat'), models.Index(fields=['activo'], name='idx_insumos_activo'), models.Index(fields=['fecha_vencimiento'], name='idx_insumos_venc')],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('detalles', models.TextField(blank=True, null=True)),
                ('ancho_trabajo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(blank=True, default='Disponible', max_length=50, null=True)),
                ('superficie_total_ha', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ultimo_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maquinas',
                'indexes': [models.Index(fields=['nombre'], name='idx_maquinas_nombre'), models.Index(fields=['marca'], name='idx_maquinas_marca'), models.Index(fields=['estado'], name='idx_maquinas_estado')],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='api.maquina')),
            ],
            options={
                'db_table': 'mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.factura')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('superficie_total_ha', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trabajos_completados', models.IntegerField(default=0)),
                ('ultimo_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_trabajo',
                'indexes': [models.Index(fields=['trabajo'], name='idx_tipo_trabajo_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='Pendiente', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('a_terceros', models.BooleanField(default=False)),
                ('cobrado', models.BooleanField(default=False)),
                ('monto_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio_contratado', models.BooleanField(default=False)),
                ('rinde_cosecha', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('humedad_cosecha', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='api.campo')),
                ('id_tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='api.tipotrabajo')),
            ],
            options={
                'db_table': 'trabajos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('es_cobro', models.BooleanField(default=False)),
                ('destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('cobrar_a', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pago_limite', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.factura')),
                ('id_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trabajo')),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('destinatario', models.CharField(max_length=255)),
                ('pagado', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago_limite', models.DateField(blank=True, null=True)),
                ('es_cobro', models.BooleanField(default=False)),
                ('cobrar_a', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos', to='api.trabajo')),
            ],
            options={
                'db_table': 'costos',
            },
        ),
        migrations.CreateModel(
            name='TrabajoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maquina')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajo')),
            ],
            options={
                'db_table': 'trabajo_maquinas',
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='maquinas',
            field=models.ManyToManyField(related_name='trabajos', through='api.TrabajoMaquina', to='api.maquina'),
        ),
        migrations.CreateModel(
            name='TrabajoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personal')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trabajo')),
            ],
            options={
                'db_table': 'trabajo_personal',
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='personal',
            field=models.ManyToManyField(related_name='trabajos', through='api.TrabajoPersonal', to='api.personal'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='idx_usuarios_email'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuarios_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['activo'], name='idx_usuarios_activo'),
        ),
        migrations.AddIndex(
            model_name='campocliente',
            index=models.Index(fields=['cliente'], name='idx_campo_cliente_cli'),
        ),
        migrations.AddIndex(
            model_name='campocliente',
            index=models.Index(fields=['campo'], name='idx_campo_cliente_camp'),
        ),
        migrations.AddIndex(
            model_name='campocliente',
            index=models.Index(fields=['activo'], name='idx_campo_cliente_act'),
        ),
        migrations.AlterUniqueTogether(
            name='campocliente',
            unique_together={('cliente', 'campo', 'activo')},
        ),
        migrations.AddIndex(
            model_name='cuotacredito',
            index=models.Index(fields=['credito'], name='idx_cuotas_cred'),
        ),
        migrations.AddIndex(
            model_name='cuotacredito',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_cuotas_venc'),
        ),
        migrations.AddIndex(
            model_name='cuotacredito',
            index=models.Index(fields=['estado'], name='idx_cuotas_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotacredito',
            unique_together={('credito', 'numero_cuota')},
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente'], name='idx_facturas_cli'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='idx_facturas_num'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='idx_facturas_emision'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_facturas_venc'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='idx_facturas_estado'),
        ),
        migrations.AddIndex(
            model_name='facturaitem',
            index=models.Index(fields=['factura'], name='idx_factura_items_fac'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['maquina'], name='idx_mantenimientos_maq'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['fecha'], name='idx_mantenimientos_fecha'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado'], name='idx_mantenimientos_estado'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha'], name='idx_pagos_fecha'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['id_factura'], name='idx_pagos_factura'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='idx_pagos_metodo'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['nombre'], name='idx_personal_nombre'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['dni'], name='idx_personal_dni'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['telefono'], name='idx_personal_tel'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha'], name='idx_movs_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['pagado'], name='idx_movs_pagado'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['es_cobro'], name='idx_movs_es_cobro'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['categoria'], name='idx_movs_cat'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['id_trabajo'], name='idx_movs_trabajo'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['id_factura'], name='idx_movs_factura'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha_pago_limite'], name='idx_movs_limite'),
        ),
        migrations.AddIndex(
            model_name='costo',
            index=models.Index(fields=['fecha'], name='idx_costos_fecha'),
        ),
        migrations.AddIndex(
            model_name='costo',
            index=models.Index(fields=['pagado'], name='idx_costos_pagado'),
        ),
        migrations.AddIndex(
            model_name='costo',
            index=models.Index(fields=['es_cobro'], name='idx_costos_es_cobro'),
        ),
        migrations.AddIndex(
            model_name='costo',
            index=models.Index(fields=['categoria'], name='idx_costos_categoria'),
        ),
        migrations.AddIndex(
            model_name='costo',
            index=models.Index(fields=['id_trabajo'], name='idx_costos_trabajo'),
        ),
        migrations.AddIndex(
            model_name='costo',
            index=models.Index(fields=['fecha_pago_limite'], name='idx_costos_limite'),
        ),
        migrations.AddIndex(
            model_name='trabajomaquina',
            index=models.Index(fields=['trabajo'], name='idx_tm_trabajo'),
        ),
        migrations.AddIndex(
            model_name='trabajomaquina',
            index=models.Index(fields=['maquina'], name='idx_tm_maquina'),
        ),
        migrations.AlterUniqueTogether(
            name='trabajomaquina',
            unique_together={('trabajo', 'maquina')},
        ),
        migrations.AddIndex(
            model_name='trabajopersonal',
            index=models.Index(fields=['trabajo'], name='idx_tp_trabajo'),
        ),
        migrations.AddIndex(
            model_name='trabajopersonal',
            index=models.Index(fields=['personal'], name='idx_tp_personal'),
        ),
        migrations.AlterUniqueTogether(
            name='trabajopersonal',
            unique_together={('trabajo', 'personal')},
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['id_tipo_trabajo'], name='idx_trabajos_tipo'),
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['campo'], name='idx_trabajos_campo'),
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['fecha_inicio'], name='idx_trabajos_inicio'),
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['estado'], name='idx_trabajos_estado'),
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['cobrado'], name='idx_trabajos_cobrado'),
        ),
        migrations.AddIndex(
            model_name='trabajo',
            index=models.Index(fields=['a_terceros'], name='idx_trabajos_terceros'),
        ),
    ]
