# Generated by Django 5.2 on 2026-01-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('usuario_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'auth_tokens',
            },
        ),
        migrations.RemoveIndex(
            model_name='campo',
            name='idx_campos_nombre',
        ),
        migrations.RemoveIndex(
            model_name='campo',
            name='idx_campos_hectareas',
        ),
        migrations.RemoveIndex(
            model_name='campocliente',
            name='idx_campo_cliente_cli',
        ),
        migrations.RemoveIndex(
            model_name='campocliente',
            name='idx_campo_cliente_camp',
        ),
        migrations.RemoveIndex(
            model_name='campocliente',
            name='idx_campo_cliente_act',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='idx_clientes_nombre',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='idx_clientes_cuit',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='idx_clientes_email',
        ),
        migrations.RemoveIndex(
            model_name='costo',
            name='idx_costos_fecha',
        ),
        migrations.RemoveIndex(
            model_name='costo',
            name='idx_costos_pagado',
        ),
        migrations.RemoveIndex(
            model_name='costo',
            name='idx_costos_es_cobro',
        ),
        migrations.RemoveIndex(
            model_name='costo',
            name='idx_costos_categoria',
        ),
        migrations.RemoveIndex(
            model_name='costo',
            name='idx_costos_trabajo',
        ),
        migrations.RemoveIndex(
            model_name='costo',
            name='idx_costos_limite',
        ),
        migrations.RemoveIndex(
            model_name='credito',
            name='idx_creditos_entidad',
        ),
        migrations.RemoveIndex(
            model_name='credito',
            name='idx_creditos_estado',
        ),
        migrations.RemoveIndex(
            model_name='credito',
            name='idx_creditos_fecha',
        ),
        migrations.RemoveIndex(
            model_name='cuotacredito',
            name='idx_cuotas_cred',
        ),
        migrations.RemoveIndex(
            model_name='cuotacredito',
            name='idx_cuotas_venc',
        ),
        migrations.RemoveIndex(
            model_name='cuotacredito',
            name='idx_cuotas_estado',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='idx_facturas_cli',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='idx_facturas_num',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='idx_facturas_emision',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='idx_facturas_venc',
        ),
        migrations.RemoveIndex(
            model_name='factura',
            name='idx_facturas_estado',
        ),
        migrations.RemoveIndex(
            model_name='facturaitem',
            name='idx_factura_items_fac',
        ),
        migrations.RemoveIndex(
            model_name='insumo',
            name='idx_insumos_nombre',
        ),
        migrations.RemoveIndex(
            model_name='insumo',
            name='idx_insumos_cat',
        ),
        migrations.RemoveIndex(
            model_name='insumo',
            name='idx_insumos_activo',
        ),
        migrations.RemoveIndex(
            model_name='insumo',
            name='idx_insumos_venc',
        ),
        migrations.RemoveIndex(
            model_name='mantenimiento',
            name='idx_mantenimientos_maq',
        ),
        migrations.RemoveIndex(
            model_name='mantenimiento',
            name='idx_mantenimientos_fecha',
        ),
        migrations.RemoveIndex(
            model_name='mantenimiento',
            name='idx_mantenimientos_estado',
        ),
        migrations.RemoveIndex(
            model_name='maquina',
            name='idx_maquinas_nombre',
        ),
        migrations.RemoveIndex(
            model_name='maquina',
            name='idx_maquinas_marca',
        ),
        migrations.RemoveIndex(
            model_name='maquina',
            name='idx_maquinas_estado',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_fecha',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_pagado',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_es_cobro',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_cat',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_trabajo',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_factura',
        ),
        migrations.RemoveIndex(
            model_name='movimiento',
            name='idx_movs_limite',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='idx_pagos_fecha',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='idx_pagos_factura',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='idx_pagos_metodo',
        ),
        migrations.RemoveIndex(
            model_name='personal',
            name='idx_personal_nombre',
        ),
        migrations.RemoveIndex(
            model_name='personal',
            name='idx_personal_dni',
        ),
        migrations.RemoveIndex(
            model_name='personal',
            name='idx_personal_tel',
        ),
        migrations.RemoveIndex(
            model_name='tipotrabajo',
            name='idx_tipo_trabajo_nombre',
        ),
        migrations.RemoveIndex(
            model_name='trabajo',
            name='idx_trabajos_tipo',
        ),
        migrations.RemoveIndex(
            model_name='trabajo',
            name='idx_trabajos_campo',
        ),
        migrations.RemoveIndex(
            model_name='trabajo',
            name='idx_trabajos_inicio',
        ),
        migrations.RemoveIndex(
            model_name='trabajo',
            name='idx_trabajos_estado',
        ),
        migrations.RemoveIndex(
            model_name='trabajo',
            name='idx_trabajos_cobrado',
        ),
        migrations.RemoveIndex(
            model_name='trabajo',
            name='idx_trabajos_terceros',
        ),
        migrations.RemoveIndex(
            model_name='trabajomaquina',
            name='idx_tm_trabajo',
        ),
        migrations.RemoveIndex(
            model_name='trabajomaquina',
            name='idx_tm_maquina',
        ),
        migrations.RemoveIndex(
            model_name='trabajopersonal',
            name='idx_tp_trabajo',
        ),
        migrations.RemoveIndex(
            model_name='trabajopersonal',
            name='idx_tp_personal',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='idx_usuarios_email',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='idx_usuarios_rol',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='idx_usuarios_activo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_acceso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='campo',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='campocliente',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='costo',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajopersonal',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='hectareas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campocliente',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='campocliente',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='api.campo'),
        ),
        migrations.AlterField(
            model_name='campocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos_asignados', to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='destinatario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='es_cobro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='id_trabajo',
            field=models.ForeignKey(blank=True, db_column='id_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos', to='api.trabajo'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='pagado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='entidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_desembolso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='monto_otorgado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='plazo_meses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tasa_interes_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cuotacredito',
            name='credito',
            field=models.ForeignKey(blank=True, db_column='id_credito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='api.credito'),
        ),
        migrations.AlterField(
            model_name='cuotacredito',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuotacredito',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuotacredito',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cuotacredito',
            name='numero_cuota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.factura'),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='maquina',
            field=models.ForeignKey(blank=True, db_column='id_maquina', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='api.maquina'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='superficie_total_ha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='es_cobro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_factura',
            field=models.ForeignKey(blank=True, db_column='id_factura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.factura'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_trabajo',
            field=models.ForeignKey(blank=True, db_column='id_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trabajo'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='pagado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_factura',
            field=models.ForeignKey(blank=True, db_column='id_factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.factura'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='superficie_total_ha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='trabajos_completados',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tipotrabajo',
            name='trabajo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='a_terceros',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='api.campo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='cobrado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='cultivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='humedad_cosecha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='id_tipo_trabajo',
            field=models.ForeignKey(blank=True, db_column='id_tipo_trabajo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='api.tipotrabajo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='rinde_cosecha',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='servicio_contratado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trabajomaquina',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.maquina'),
        ),
        migrations.AlterField(
            model_name='trabajomaquina',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajopersonal',
            name='hectareas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trabajopersonal',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AlterField(
            model_name='trabajopersonal',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='activo', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Contable', 'Contable'), ('Operario', 'Operario')], default='Operario', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['access_token'], name='auth_tokens_access__f9680e_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['usuario_id'], name='auth_tokens_usuario_bece6a_idx'),
        ),
    ]
