# Generated by Django 5.2 on 2026-01-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_authtoken_remove_campo_idx_campos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='cliente_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='propio',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
