# Generated by Django 5.2 on 2026-01-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_cliente_id_and_propio_to_campo'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trabajopersonal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trabajopersonal',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajopersonal',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajopersonal',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajopersonal',
            name='usuario_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
