# Generated by Django 4.2.28 on 2026-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_lotes_indicaciones_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='access_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='usuario_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campo',
            name='propio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
