# Generated by Django 4.2.28 on 2026-09-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usuario_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Productor', 'Productor'), ('Prestador', 'Prestador'), ('Ambos', 'Ambos')], default='Productor', max_length=20)),
                ('nombre_publico', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=50)),
                ('localidad', models.CharField(blank=True, default='', max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('radio_cobertura_km', models.PositiveIntegerField(default=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_marketplace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles_marketplace',
            },
        ),
        migrations.CreateModel(
            name='ServicioMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radio_cobertura_km', models.PositiveIntegerField(default=50)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_marketplace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'servicios_marketplace',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['categoria', 'disponible'], name='servicios_m_categor_cca4ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='PedidoServicioMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_necesaria', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Publicado', 'Publicado'), ('Pausado', 'Pausado'), ('Cerrado', 'Cerrado')], default='Publicado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_marketplace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos_servicio_marketplace',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['categoria', 'estado'], name='pedidos_ser_categor_c63063_idx')],
            },
        ),
    ]
