# Generated by Django 4.2.28 on 2026-09-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_perfilmarketplace_serviciomarketplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoserviciomarketplace',
            name='radio_cobertura_km',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
